# SonarQube Project Identification
sonar.projectKey=Chicotelamion
sonar.organization=Chicotelamion_Chicote16

# Source folders
sonar.sources=lib,app

# Excluded files
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
